import { createTheme } from "@mantine/core";
import * as tokens from "./tokens/tokens.ts";

const theme = createTheme({
  /** Configuração do tema do Mantine */
  fontFamily: "Raleway Variable, sans-serif",
  colors: {
    "blue-cool-vivid": [
      tokens.siseunColorBlueCoolVivid5,
      tokens.siseunColorBlueCoolVivid10,
      tokens.siseunColorBlueCoolVivid20,
      tokens.siseunColorBlueCoolVivid30,
      tokens.siseunColorBlueCoolVivid40,
      tokens.siseunColorBlueCoolVivid50,
      tokens.siseunColorBlueCoolVivid60,
      tokens.siseunColorBlueCoolVivid70,
      tokens.siseunColorBlueCoolVivid80,
      tokens.siseunColorBlueCoolVivid80,
    ],
    "blue-cool": [
      tokens.siseunColorBlueCool5,
      tokens.siseunColorBlueCool10,
      tokens.siseunColorBlueCool20,
      tokens.siseunColorBlueCool30,
      tokens.siseunColorBlueCool40,
      tokens.siseunColorBlueCool50,
      tokens.siseunColorBlueCool60,
      tokens.siseunColorBlueCool70,
      tokens.siseunColorBlueCool80,
      tokens.siseunColorBlueCool90,
    ],
    "blue-vivid": [
      tokens.siseunColorBlueVivid5,
      tokens.siseunColorBlueVivid10,
      tokens.siseunColorBlueVivid20,
      tokens.siseunColorBlueVivid30,
      tokens.siseunColorBlueVivid40,
      tokens.siseunColorBlueVivid50,
      tokens.siseunColorBlueVivid60,
      tokens.siseunColorBlueVivid70,
      tokens.siseunColorBlueVivid80,
      tokens.siseunColorBlueVivid80,
    ],
    "blue-warm-vivid": [
      tokens.siseunColorBlueWarmVivid5,
      tokens.siseunColorBlueWarmVivid10,
      tokens.siseunColorBlueWarmVivid20,
      tokens.siseunColorBlueWarmVivid30,
      tokens.siseunColorBlueWarmVivid40,
      tokens.siseunColorBlueWarmVivid50,
      tokens.siseunColorBlueWarmVivid60,
      tokens.siseunColorBlueWarmVivid70,
      tokens.siseunColorBlueWarmVivid80,
      tokens.siseunColorBlueWarmVivid90,
    ],
    "blue-warm": [
      tokens.siseunColorBlueWarm5,
      tokens.siseunColorBlueWarm10,
      tokens.siseunColorBlueWarm20,
      tokens.siseunColorBlueWarm30,
      tokens.siseunColorBlueWarm40,
      tokens.siseunColorBlueWarm50,
      tokens.siseunColorBlueWarm60,
      tokens.siseunColorBlueWarm70,
      tokens.siseunColorBlueWarm80,
      tokens.siseunColorBlueWarm90,
    ],
    "blue": [
      tokens.siseunColorBlue5,
      tokens.siseunColorBlue10,
      tokens.siseunColorBlue20,
      tokens.siseunColorBlue30,
      tokens.siseunColorBlue40,
      tokens.siseunColorBlue50,
      tokens.siseunColorBlue60,
      tokens.siseunColorBlue70,
      tokens.siseunColorBlue80,
      tokens.siseunColorBlue90,
    ],
    "cyan-vivid": [
      tokens.siseunColorCyanVivid5,
      tokens.siseunColorCyanVivid10,
      tokens.siseunColorCyanVivid20,
      tokens.siseunColorCyanVivid30,
      tokens.siseunColorCyanVivid40,
      tokens.siseunColorCyanVivid50,
      tokens.siseunColorCyanVivid60,
      tokens.siseunColorCyanVivid70,
      tokens.siseunColorCyanVivid80,
      tokens.siseunColorCyanVivid80,
    ],
    "cyan": [
      tokens.siseunColorCyan5,
      tokens.siseunColorCyan10,
      tokens.siseunColorCyan20,
      tokens.siseunColorCyan30,
      tokens.siseunColorCyan40,
      tokens.siseunColorCyan50,
      tokens.siseunColorCyan60,
      tokens.siseunColorCyan70,
      tokens.siseunColorCyan80,
      tokens.siseunColorCyan90,
    ],
    "gold-vivid": [
      tokens.siseunColorGoldVivid5,
      tokens.siseunColorGoldVivid10,
      tokens.siseunColorGoldVivid20,
      tokens.siseunColorGoldVivid30,
      tokens.siseunColorGoldVivid40,
      tokens.siseunColorGoldVivid50,
      tokens.siseunColorGoldVivid60,
      tokens.siseunColorGoldVivid70,
      tokens.siseunColorGoldVivid80,
      tokens.siseunColorGoldVivid80,
    ],
    "gold": [
      tokens.siseunColorGold5,
      tokens.siseunColorGold10,
      tokens.siseunColorGold20,
      tokens.siseunColorGold30,
      tokens.siseunColorGold40,
      tokens.siseunColorGold50,
      tokens.siseunColorGold60,
      tokens.siseunColorGold70,
      tokens.siseunColorGold80,
      tokens.siseunColorGold90,
    ],
    "gray-cool": [
      tokens.siseunColorGrayCool5,
      tokens.siseunColorGrayCool10,
      tokens.siseunColorGrayCool20,
      tokens.siseunColorGrayCool30,
      tokens.siseunColorGrayCool40,
      tokens.siseunColorGrayCool50,
      tokens.siseunColorGrayCool60,
      tokens.siseunColorGrayCool70,
      tokens.siseunColorGrayCool80,
      tokens.siseunColorGrayCool90,
    ],
    "gray-warm": [
      tokens.siseunColorGrayWarm5,
      tokens.siseunColorGrayWarm10,
      tokens.siseunColorGrayWarm20,
      tokens.siseunColorGrayWarm30,
      tokens.siseunColorGrayWarm40,
      tokens.siseunColorGrayWarm50,
      tokens.siseunColorGrayWarm60,
      tokens.siseunColorGrayWarm70,
      tokens.siseunColorGrayWarm80,
      tokens.siseunColorGrayWarm90,
    ],
    "gray": [
      tokens.siseunColorGray5,
      tokens.siseunColorGray10,
      tokens.siseunColorGray20,
      tokens.siseunColorGray30,
      tokens.siseunColorGray40,
      tokens.siseunColorGray50,
      tokens.siseunColorGray60,
      tokens.siseunColorGray70,
      tokens.siseunColorGray80,
      tokens.siseunColorGray90,
    ],
    "green-cool-vivid": [
      tokens.siseunColorGreenCoolVivid5,
      tokens.siseunColorGreenCoolVivid10,
      tokens.siseunColorGreenCoolVivid20,
      tokens.siseunColorGreenCoolVivid30,
      tokens.siseunColorGreenCoolVivid40,
      tokens.siseunColorGreenCoolVivid50,
      tokens.siseunColorGreenCoolVivid60,
      tokens.siseunColorGreenCoolVivid70,
      tokens.siseunColorGreenCoolVivid80,
      tokens.siseunColorGreenCoolVivid80,
    ],
    "green-cool": [
      tokens.siseunColorGreenCool5,
      tokens.siseunColorGreenCool10,
      tokens.siseunColorGreenCool20,
      tokens.siseunColorGreenCool30,
      tokens.siseunColorGreenCool40,
      tokens.siseunColorGreenCool50,
      tokens.siseunColorGreenCool60,
      tokens.siseunColorGreenCool70,
      tokens.siseunColorGreenCool80,
      tokens.siseunColorGreenCool90,
    ],
    "green-vivid": [
      tokens.siseunColorGreenVivid5,
      tokens.siseunColorGreenVivid10,
      tokens.siseunColorGreenVivid20,
      tokens.siseunColorGreenVivid30,
      tokens.siseunColorGreenVivid40,
      tokens.siseunColorGreenVivid50,
      tokens.siseunColorGreenVivid60,
      tokens.siseunColorGreenVivid70,
      tokens.siseunColorGreenVivid80,
      tokens.siseunColorGreenVivid80,
    ],
    "green-warm-vivid": [
      tokens.siseunColorGreenWarmVivid5,
      tokens.siseunColorGreenWarmVivid10,
      tokens.siseunColorGreenWarmVivid20,
      tokens.siseunColorGreenWarmVivid30,
      tokens.siseunColorGreenWarmVivid40,
      tokens.siseunColorGreenWarmVivid50,
      tokens.siseunColorGreenWarmVivid60,
      tokens.siseunColorGreenWarmVivid70,
      tokens.siseunColorGreenWarmVivid80,
      tokens.siseunColorGreenWarmVivid80,
    ],
    "green-warm": [
      tokens.siseunColorGreenWarm5,
      tokens.siseunColorGreenWarm10,
      tokens.siseunColorGreenWarm20,
      tokens.siseunColorGreenWarm30,
      tokens.siseunColorGreenWarm40,
      tokens.siseunColorGreenWarm50,
      tokens.siseunColorGreenWarm60,
      tokens.siseunColorGreenWarm70,
      tokens.siseunColorGreenWarm80,
      tokens.siseunColorGreenWarm90,
    ],
    "green": [
      tokens.siseunColorGreen5,
      tokens.siseunColorGreen10,
      tokens.siseunColorGreen20,
      tokens.siseunColorGreen30,
      tokens.siseunColorGreen40,
      tokens.siseunColorGreen50,
      tokens.siseunColorGreen60,
      tokens.siseunColorGreen70,
      tokens.siseunColorGreen80,
      tokens.siseunColorGreen90,
    ],
    "indigo-cool-vivid": [
      tokens.siseunColorIndigoCoolVivid5,
      tokens.siseunColorIndigoCoolVivid10,
      tokens.siseunColorIndigoCoolVivid20,
      tokens.siseunColorIndigoCoolVivid30,
      tokens.siseunColorIndigoCoolVivid40,
      tokens.siseunColorIndigoCoolVivid50,
      tokens.siseunColorIndigoCoolVivid60,
      tokens.siseunColorIndigoCoolVivid70,
      tokens.siseunColorIndigoCoolVivid80,
      tokens.siseunColorIndigoCoolVivid80,
    ],
    "indigo-cool": [
      tokens.siseunColorIndigoCool5,
      tokens.siseunColorIndigoCool10,
      tokens.siseunColorIndigoCool20,
      tokens.siseunColorIndigoCool30,
      tokens.siseunColorIndigoCool40,
      tokens.siseunColorIndigoCool50,
      tokens.siseunColorIndigoCool60,
      tokens.siseunColorIndigoCool70,
      tokens.siseunColorIndigoCool80,
      tokens.siseunColorIndigoCool90,
    ],
    "indigo-vivid": [
      tokens.siseunColorIndigoVivid5,
      tokens.siseunColorIndigoVivid10,
      tokens.siseunColorIndigoVivid20,
      tokens.siseunColorIndigoVivid30,
      tokens.siseunColorIndigoVivid40,
      tokens.siseunColorIndigoVivid50,
      tokens.siseunColorIndigoVivid60,
      tokens.siseunColorIndigoVivid70,
      tokens.siseunColorIndigoVivid80,
      tokens.siseunColorIndigoVivid80,
    ],
    "indigo-warm-vivid": [
      tokens.siseunColorIndigoWarmVivid5,
      tokens.siseunColorIndigoWarmVivid10,
      tokens.siseunColorIndigoWarmVivid20,
      tokens.siseunColorIndigoWarmVivid30,
      tokens.siseunColorIndigoWarmVivid40,
      tokens.siseunColorIndigoWarmVivid50,
      tokens.siseunColorIndigoWarmVivid60,
      tokens.siseunColorIndigoWarmVivid70,
      tokens.siseunColorIndigoWarmVivid80,
      tokens.siseunColorIndigoWarmVivid80,
    ],
    "indigo-warm": [
      tokens.siseunColorIndigoWarm5,
      tokens.siseunColorIndigoWarm10,
      tokens.siseunColorIndigoWarm20,
      tokens.siseunColorIndigoWarm30,
      tokens.siseunColorIndigoWarm40,
      tokens.siseunColorIndigoWarm50,
      tokens.siseunColorIndigoWarm60,
      tokens.siseunColorIndigoWarm70,
      tokens.siseunColorIndigoWarm80,
      tokens.siseunColorIndigoWarm90,
    ],
    "indigo": [
      tokens.siseunColorIndigo5,
      tokens.siseunColorIndigo10,
      tokens.siseunColorIndigo20,
      tokens.siseunColorIndigo30,
      tokens.siseunColorIndigo40,
      tokens.siseunColorIndigo50,
      tokens.siseunColorIndigo60,
      tokens.siseunColorIndigo70,
      tokens.siseunColorIndigo80,
      tokens.siseunColorIndigo90,
    ],
    "orange-vivid": [
      tokens.siseunColorOrangeVivid5,
      tokens.siseunColorOrangeVivid10,
      tokens.siseunColorOrangeVivid20,
      tokens.siseunColorOrangeVivid30,
      tokens.siseunColorOrangeVivid40,
      tokens.siseunColorOrangeVivid50,
      tokens.siseunColorOrangeVivid60,
      tokens.siseunColorOrangeVivid70,
      tokens.siseunColorOrangeVivid80,
      tokens.siseunColorOrangeVivid80,
    ],
    "orange-warm-vivid": [
      tokens.siseunColorOrangeWarmVivid5,
      tokens.siseunColorOrangeWarmVivid10,
      tokens.siseunColorOrangeWarmVivid20,
      tokens.siseunColorOrangeWarmVivid30,
      tokens.siseunColorOrangeWarmVivid40,
      tokens.siseunColorOrangeWarmVivid50,
      tokens.siseunColorOrangeWarmVivid60,
      tokens.siseunColorOrangeWarmVivid70,
      tokens.siseunColorOrangeWarmVivid80,
      tokens.siseunColorOrangeWarmVivid80,
    ],
    "orange-warm": [
      tokens.siseunColorOrangeWarm5,
      tokens.siseunColorOrangeWarm10,
      tokens.siseunColorOrangeWarm20,
      tokens.siseunColorOrangeWarm30,
      tokens.siseunColorOrangeWarm40,
      tokens.siseunColorOrangeWarm50,
      tokens.siseunColorOrangeWarm60,
      tokens.siseunColorOrangeWarm70,
      tokens.siseunColorOrangeWarm80,
      tokens.siseunColorOrangeWarm90,
    ],
    "orange": [
      tokens.siseunColorOrange5,
      tokens.siseunColorOrange10,
      tokens.siseunColorOrange20,
      tokens.siseunColorOrange30,
      tokens.siseunColorOrange40,
      tokens.siseunColorOrange50,
      tokens.siseunColorOrange60,
      tokens.siseunColorOrange70,
      tokens.siseunColorOrange80,
      tokens.siseunColorOrange90,
    ],
    "red-cool-vivid": [
      tokens.siseunColorRedCoolVivid5,
      tokens.siseunColorRedCoolVivid10,
      tokens.siseunColorRedCoolVivid20,
      tokens.siseunColorRedCoolVivid30,
      tokens.siseunColorRedCoolVivid40,
      tokens.siseunColorRedCoolVivid50,
      tokens.siseunColorRedCoolVivid60,
      tokens.siseunColorRedCoolVivid70,
      tokens.siseunColorRedCoolVivid80,
      tokens.siseunColorRedCoolVivid80,
    ],
    "red-cool": [
      tokens.siseunColorRedCool5,
      tokens.siseunColorRedCool10,
      tokens.siseunColorRedCool20,
      tokens.siseunColorRedCool30,
      tokens.siseunColorRedCool40,
      tokens.siseunColorRedCool50,
      tokens.siseunColorRedCool60,
      tokens.siseunColorRedCool70,
      tokens.siseunColorRedCool80,
      tokens.siseunColorRedCool90,
    ],
    "red-vivid": [
      tokens.siseunColorRedVivid5,
      tokens.siseunColorRedVivid10,
      tokens.siseunColorRedVivid20,
      tokens.siseunColorRedVivid30,
      tokens.siseunColorRedVivid40,
      tokens.siseunColorRedVivid50,
      tokens.siseunColorRedVivid60,
      tokens.siseunColorRedVivid70,
      tokens.siseunColorRedVivid80,
      tokens.siseunColorRedVivid80,
    ],
    "red-warm-vivid": [
      tokens.siseunColorRedWarmVivid5,
      tokens.siseunColorRedWarmVivid10,
      tokens.siseunColorRedWarmVivid20,
      tokens.siseunColorRedWarmVivid30,
      tokens.siseunColorRedWarmVivid40,
      tokens.siseunColorRedWarmVivid50,
      tokens.siseunColorRedWarmVivid60,
      tokens.siseunColorRedWarmVivid70,
      tokens.siseunColorRedWarmVivid80,
      tokens.siseunColorRedWarmVivid80,
    ],
    "red-warm": [
      tokens.siseunColorRedWarm5,
      tokens.siseunColorRedWarm10,
      tokens.siseunColorRedWarm20,
      tokens.siseunColorRedWarm30,
      tokens.siseunColorRedWarm40,
      tokens.siseunColorRedWarm50,
      tokens.siseunColorRedWarm60,
      tokens.siseunColorRedWarm70,
      tokens.siseunColorRedWarm80,
      tokens.siseunColorRedWarm90,
    ],
    "red": [
      tokens.siseunColorRed5,
      tokens.siseunColorRed10,
      tokens.siseunColorRed20,
      tokens.siseunColorRed30,
      tokens.siseunColorRed40,
      tokens.siseunColorRed50,
      tokens.siseunColorRed60,
      tokens.siseunColorRed70,
      tokens.siseunColorRed80,
      tokens.siseunColorRed90,
    ],
    "yellow-vivid": [
      tokens.siseunColorYellowVivid5,
      tokens.siseunColorYellowVivid10,
      tokens.siseunColorYellowVivid20,
      tokens.siseunColorYellowVivid30,
      tokens.siseunColorYellowVivid40,
      tokens.siseunColorYellowVivid50,
      tokens.siseunColorYellowVivid60,
      tokens.siseunColorYellowVivid70,
      tokens.siseunColorYellowVivid80,
      tokens.siseunColorYellowVivid80,
    ],
    "yellow": [
      tokens.siseunColorYellow5,
      tokens.siseunColorYellow10,
      tokens.siseunColorYellow20,
      tokens.siseunColorYellow30,
      tokens.siseunColorYellow40,
      tokens.siseunColorYellow50,
      tokens.siseunColorYellow60,
      tokens.siseunColorYellow70,
      tokens.siseunColorYellow80,
      tokens.siseunColorYellow90,
    ],
  },
});

export default theme;
