import { createTheme } from "@mantine/core";
import * as sisEunTokens from "./tokens/tokens.ts";

const theme = createTheme({
  /** Configuração do tema do Mantine */
  fontFamily: "Raleway Variable, sans-serif",
  colors: {
    "blue-cool-vivid": [
      sisEunTokens.siseunColorBlueCoolVivid5,
      sisEunTokens.siseunColorBlueCoolVivid10,
      sisEunTokens.siseunColorBlueCoolVivid20,
      sisEunTokens.siseunColorBlueCoolVivid30,
      sisEunTokens.siseunColorBlueCoolVivid40,
      sisEunTokens.siseunColorBlueCoolVivid50,
      sisEunTokens.siseunColorBlueCoolVivid60,
      sisEunTokens.siseunColorBlueCoolVivid70,
      sisEunTokens.siseunColorBlueCoolVivid80,
      sisEunTokens.siseunColorBlueCoolVivid80,
    ],
    "blue-cool": [
      sisEunTokens.siseunColorBlueCool5,
      sisEunTokens.siseunColorBlueCool10,
      sisEunTokens.siseunColorBlueCool20,
      sisEunTokens.siseunColorBlueCool30,
      sisEunTokens.siseunColorBlueCool40,
      sisEunTokens.siseunColorBlueCool50,
      sisEunTokens.siseunColorBlueCool60,
      sisEunTokens.siseunColorBlueCool70,
      sisEunTokens.siseunColorBlueCool80,
      sisEunTokens.siseunColorBlueCool90,
    ],
    "blue-vivid": [
      sisEunTokens.siseunColorBlueVivid5,
      sisEunTokens.siseunColorBlueVivid10,
      sisEunTokens.siseunColorBlueVivid20,
      sisEunTokens.siseunColorBlueVivid30,
      sisEunTokens.siseunColorBlueVivid40,
      sisEunTokens.siseunColorBlueVivid50,
      sisEunTokens.siseunColorBlueVivid60,
      sisEunTokens.siseunColorBlueVivid70,
      sisEunTokens.siseunColorBlueVivid80,
      sisEunTokens.siseunColorBlueVivid80,
    ],
    "blue-warm-vivid": [
      sisEunTokens.siseunColorBlueWarmVivid5,
      sisEunTokens.siseunColorBlueWarmVivid10,
      sisEunTokens.siseunColorBlueWarmVivid20,
      sisEunTokens.siseunColorBlueWarmVivid30,
      sisEunTokens.siseunColorBlueWarmVivid40,
      sisEunTokens.siseunColorBlueWarmVivid50,
      sisEunTokens.siseunColorBlueWarmVivid60,
      sisEunTokens.siseunColorBlueWarmVivid70,
      sisEunTokens.siseunColorBlueWarmVivid80,
      sisEunTokens.siseunColorBlueWarmVivid90,
    ],
    "blue-warm": [
      sisEunTokens.siseunColorBlueWarm5,
      sisEunTokens.siseunColorBlueWarm10,
      sisEunTokens.siseunColorBlueWarm20,
      sisEunTokens.siseunColorBlueWarm30,
      sisEunTokens.siseunColorBlueWarm40,
      sisEunTokens.siseunColorBlueWarm50,
      sisEunTokens.siseunColorBlueWarm60,
      sisEunTokens.siseunColorBlueWarm70,
      sisEunTokens.siseunColorBlueWarm80,
      sisEunTokens.siseunColorBlueWarm90,
    ],
    "blue": [
      sisEunTokens.siseunColorBlue5,
      sisEunTokens.siseunColorBlue10,
      sisEunTokens.siseunColorBlue20,
      sisEunTokens.siseunColorBlue30,
      sisEunTokens.siseunColorBlue40,
      sisEunTokens.siseunColorBlue50,
      sisEunTokens.siseunColorBlue60,
      sisEunTokens.siseunColorBlue70,
      sisEunTokens.siseunColorBlue80,
      sisEunTokens.siseunColorBlue90,
    ],
    "cyan-vivid": [
      sisEunTokens.siseunColorCyanVivid5,
      sisEunTokens.siseunColorCyanVivid10,
      sisEunTokens.siseunColorCyanVivid20,
      sisEunTokens.siseunColorCyanVivid30,
      sisEunTokens.siseunColorCyanVivid40,
      sisEunTokens.siseunColorCyanVivid50,
      sisEunTokens.siseunColorCyanVivid60,
      sisEunTokens.siseunColorCyanVivid70,
      sisEunTokens.siseunColorCyanVivid80,
      sisEunTokens.siseunColorCyanVivid80,
    ],
    "cyan": [
      sisEunTokens.siseunColorCyan5,
      sisEunTokens.siseunColorCyan10,
      sisEunTokens.siseunColorCyan20,
      sisEunTokens.siseunColorCyan30,
      sisEunTokens.siseunColorCyan40,
      sisEunTokens.siseunColorCyan50,
      sisEunTokens.siseunColorCyan60,
      sisEunTokens.siseunColorCyan70,
      sisEunTokens.siseunColorCyan80,
      sisEunTokens.siseunColorCyan90,
    ],
    "gold-vivid": [
      sisEunTokens.siseunColorGoldVivid5,
      sisEunTokens.siseunColorGoldVivid10,
      sisEunTokens.siseunColorGoldVivid20,
      sisEunTokens.siseunColorGoldVivid30,
      sisEunTokens.siseunColorGoldVivid40,
      sisEunTokens.siseunColorGoldVivid50,
      sisEunTokens.siseunColorGoldVivid60,
      sisEunTokens.siseunColorGoldVivid70,
      sisEunTokens.siseunColorGoldVivid80,
      sisEunTokens.siseunColorGoldVivid80,
    ],
    "gold": [
      sisEunTokens.siseunColorGold5,
      sisEunTokens.siseunColorGold10,
      sisEunTokens.siseunColorGold20,
      sisEunTokens.siseunColorGold30,
      sisEunTokens.siseunColorGold40,
      sisEunTokens.siseunColorGold50,
      sisEunTokens.siseunColorGold60,
      sisEunTokens.siseunColorGold70,
      sisEunTokens.siseunColorGold80,
      sisEunTokens.siseunColorGold90,
    ],
    "gray-cool": [
      sisEunTokens.siseunColorGrayCool5,
      sisEunTokens.siseunColorGrayCool10,
      sisEunTokens.siseunColorGrayCool20,
      sisEunTokens.siseunColorGrayCool30,
      sisEunTokens.siseunColorGrayCool40,
      sisEunTokens.siseunColorGrayCool50,
      sisEunTokens.siseunColorGrayCool60,
      sisEunTokens.siseunColorGrayCool70,
      sisEunTokens.siseunColorGrayCool80,
      sisEunTokens.siseunColorGrayCool90,
    ],
    "gray-warm": [
      sisEunTokens.siseunColorGrayWarm5,
      sisEunTokens.siseunColorGrayWarm10,
      sisEunTokens.siseunColorGrayWarm20,
      sisEunTokens.siseunColorGrayWarm30,
      sisEunTokens.siseunColorGrayWarm40,
      sisEunTokens.siseunColorGrayWarm50,
      sisEunTokens.siseunColorGrayWarm60,
      sisEunTokens.siseunColorGrayWarm70,
      sisEunTokens.siseunColorGrayWarm80,
      sisEunTokens.siseunColorGrayWarm90,
    ],
    "gray": [
      sisEunTokens.siseunColorGray5,
      sisEunTokens.siseunColorGray10,
      sisEunTokens.siseunColorGray20,
      sisEunTokens.siseunColorGray30,
      sisEunTokens.siseunColorGray40,
      sisEunTokens.siseunColorGray50,
      sisEunTokens.siseunColorGray60,
      sisEunTokens.siseunColorGray70,
      sisEunTokens.siseunColorGray80,
      sisEunTokens.siseunColorGray90,
    ],
    "green-cool-vivid": [
      sisEunTokens.siseunColorGreenCoolVivid5,
      sisEunTokens.siseunColorGreenCoolVivid10,
      sisEunTokens.siseunColorGreenCoolVivid20,
      sisEunTokens.siseunColorGreenCoolVivid30,
      sisEunTokens.siseunColorGreenCoolVivid40,
      sisEunTokens.siseunColorGreenCoolVivid50,
      sisEunTokens.siseunColorGreenCoolVivid60,
      sisEunTokens.siseunColorGreenCoolVivid70,
      sisEunTokens.siseunColorGreenCoolVivid80,
      sisEunTokens.siseunColorGreenCoolVivid80,
    ],
    "green-cool": [
      sisEunTokens.siseunColorGreenCool5,
      sisEunTokens.siseunColorGreenCool10,
      sisEunTokens.siseunColorGreenCool20,
      sisEunTokens.siseunColorGreenCool30,
      sisEunTokens.siseunColorGreenCool40,
      sisEunTokens.siseunColorGreenCool50,
      sisEunTokens.siseunColorGreenCool60,
      sisEunTokens.siseunColorGreenCool70,
      sisEunTokens.siseunColorGreenCool80,
      sisEunTokens.siseunColorGreenCool90,
    ],
    "green-vivid": [
      sisEunTokens.siseunColorGreenVivid5,
      sisEunTokens.siseunColorGreenVivid10,
      sisEunTokens.siseunColorGreenVivid20,
      sisEunTokens.siseunColorGreenVivid30,
      sisEunTokens.siseunColorGreenVivid40,
      sisEunTokens.siseunColorGreenVivid50,
      sisEunTokens.siseunColorGreenVivid60,
      sisEunTokens.siseunColorGreenVivid70,
      sisEunTokens.siseunColorGreenVivid80,
      sisEunTokens.siseunColorGreenVivid80,
    ],
    "green-warm-vivid": [
      sisEunTokens.siseunColorGreenWarmVivid5,
      sisEunTokens.siseunColorGreenWarmVivid10,
      sisEunTokens.siseunColorGreenWarmVivid20,
      sisEunTokens.siseunColorGreenWarmVivid30,
      sisEunTokens.siseunColorGreenWarmVivid40,
      sisEunTokens.siseunColorGreenWarmVivid50,
      sisEunTokens.siseunColorGreenWarmVivid60,
      sisEunTokens.siseunColorGreenWarmVivid70,
      sisEunTokens.siseunColorGreenWarmVivid80,
      sisEunTokens.siseunColorGreenWarmVivid80,
    ],
    "green-warm": [
      sisEunTokens.siseunColorGreenWarm5,
      sisEunTokens.siseunColorGreenWarm10,
      sisEunTokens.siseunColorGreenWarm20,
      sisEunTokens.siseunColorGreenWarm30,
      sisEunTokens.siseunColorGreenWarm40,
      sisEunTokens.siseunColorGreenWarm50,
      sisEunTokens.siseunColorGreenWarm60,
      sisEunTokens.siseunColorGreenWarm70,
      sisEunTokens.siseunColorGreenWarm80,
      sisEunTokens.siseunColorGreenWarm90,
    ],
    "green": [
      sisEunTokens.siseunColorGreen5,
      sisEunTokens.siseunColorGreen10,
      sisEunTokens.siseunColorGreen20,
      sisEunTokens.siseunColorGreen30,
      sisEunTokens.siseunColorGreen40,
      sisEunTokens.siseunColorGreen50,
      sisEunTokens.siseunColorGreen60,
      sisEunTokens.siseunColorGreen70,
      sisEunTokens.siseunColorGreen80,
      sisEunTokens.siseunColorGreen90,
    ],
    "indigo-cool-vivid": [
      sisEunTokens.siseunColorIndigoCoolVivid5,
      sisEunTokens.siseunColorIndigoCoolVivid10,
      sisEunTokens.siseunColorIndigoCoolVivid20,
      sisEunTokens.siseunColorIndigoCoolVivid30,
      sisEunTokens.siseunColorIndigoCoolVivid40,
      sisEunTokens.siseunColorIndigoCoolVivid50,
      sisEunTokens.siseunColorIndigoCoolVivid60,
      sisEunTokens.siseunColorIndigoCoolVivid70,
      sisEunTokens.siseunColorIndigoCoolVivid80,
      sisEunTokens.siseunColorIndigoCoolVivid80,
    ],
    "indigo-cool": [
      sisEunTokens.siseunColorIndigoCool5,
      sisEunTokens.siseunColorIndigoCool10,
      sisEunTokens.siseunColorIndigoCool20,
      sisEunTokens.siseunColorIndigoCool30,
      sisEunTokens.siseunColorIndigoCool40,
      sisEunTokens.siseunColorIndigoCool50,
      sisEunTokens.siseunColorIndigoCool60,
      sisEunTokens.siseunColorIndigoCool70,
      sisEunTokens.siseunColorIndigoCool80,
      sisEunTokens.siseunColorIndigoCool90,
    ],
    "indigo-vivid": [
      sisEunTokens.siseunColorIndigoVivid5,
      sisEunTokens.siseunColorIndigoVivid10,
      sisEunTokens.siseunColorIndigoVivid20,
      sisEunTokens.siseunColorIndigoVivid30,
      sisEunTokens.siseunColorIndigoVivid40,
      sisEunTokens.siseunColorIndigoVivid50,
      sisEunTokens.siseunColorIndigoVivid60,
      sisEunTokens.siseunColorIndigoVivid70,
      sisEunTokens.siseunColorIndigoVivid80,
      sisEunTokens.siseunColorIndigoVivid80,
    ],
    "indigo-warm-vivid": [
      sisEunTokens.siseunColorIndigoWarmVivid5,
      sisEunTokens.siseunColorIndigoWarmVivid10,
      sisEunTokens.siseunColorIndigoWarmVivid20,
      sisEunTokens.siseunColorIndigoWarmVivid30,
      sisEunTokens.siseunColorIndigoWarmVivid40,
      sisEunTokens.siseunColorIndigoWarmVivid50,
      sisEunTokens.siseunColorIndigoWarmVivid60,
      sisEunTokens.siseunColorIndigoWarmVivid70,
      sisEunTokens.siseunColorIndigoWarmVivid80,
      sisEunTokens.siseunColorIndigoWarmVivid80,
    ],
    "indigo-warm": [
      sisEunTokens.siseunColorIndigoWarm5,
      sisEunTokens.siseunColorIndigoWarm10,
      sisEunTokens.siseunColorIndigoWarm20,
      sisEunTokens.siseunColorIndigoWarm30,
      sisEunTokens.siseunColorIndigoWarm40,
      sisEunTokens.siseunColorIndigoWarm50,
      sisEunTokens.siseunColorIndigoWarm60,
      sisEunTokens.siseunColorIndigoWarm70,
      sisEunTokens.siseunColorIndigoWarm80,
      sisEunTokens.siseunColorIndigoWarm90,
    ],
    "indigo": [
      sisEunTokens.siseunColorIndigo5,
      sisEunTokens.siseunColorIndigo10,
      sisEunTokens.siseunColorIndigo20,
      sisEunTokens.siseunColorIndigo30,
      sisEunTokens.siseunColorIndigo40,
      sisEunTokens.siseunColorIndigo50,
      sisEunTokens.siseunColorIndigo60,
      sisEunTokens.siseunColorIndigo70,
      sisEunTokens.siseunColorIndigo80,
      sisEunTokens.siseunColorIndigo90,
    ],
    "orange-vivid": [
      sisEunTokens.siseunColorOrangeVivid5,
      sisEunTokens.siseunColorOrangeVivid10,
      sisEunTokens.siseunColorOrangeVivid20,
      sisEunTokens.siseunColorOrangeVivid30,
      sisEunTokens.siseunColorOrangeVivid40,
      sisEunTokens.siseunColorOrangeVivid50,
      sisEunTokens.siseunColorOrangeVivid60,
      sisEunTokens.siseunColorOrangeVivid70,
      sisEunTokens.siseunColorOrangeVivid80,
      sisEunTokens.siseunColorOrangeVivid80,
    ],
    "orange-warm-vivid": [
      sisEunTokens.siseunColorOrangeWarmVivid5,
      sisEunTokens.siseunColorOrangeWarmVivid10,
      sisEunTokens.siseunColorOrangeWarmVivid20,
      sisEunTokens.siseunColorOrangeWarmVivid30,
      sisEunTokens.siseunColorOrangeWarmVivid40,
      sisEunTokens.siseunColorOrangeWarmVivid50,
      sisEunTokens.siseunColorOrangeWarmVivid60,
      sisEunTokens.siseunColorOrangeWarmVivid70,
      sisEunTokens.siseunColorOrangeWarmVivid80,
      sisEunTokens.siseunColorOrangeWarmVivid80,
    ],
    "orange-warm": [
      sisEunTokens.siseunColorOrangeWarm5,
      sisEunTokens.siseunColorOrangeWarm10,
      sisEunTokens.siseunColorOrangeWarm20,
      sisEunTokens.siseunColorOrangeWarm30,
      sisEunTokens.siseunColorOrangeWarm40,
      sisEunTokens.siseunColorOrangeWarm50,
      sisEunTokens.siseunColorOrangeWarm60,
      sisEunTokens.siseunColorOrangeWarm70,
      sisEunTokens.siseunColorOrangeWarm80,
      sisEunTokens.siseunColorOrangeWarm90,
    ],
    "orange": [
      sisEunTokens.siseunColorOrange5,
      sisEunTokens.siseunColorOrange10,
      sisEunTokens.siseunColorOrange20,
      sisEunTokens.siseunColorOrange30,
      sisEunTokens.siseunColorOrange40,
      sisEunTokens.siseunColorOrange50,
      sisEunTokens.siseunColorOrange60,
      sisEunTokens.siseunColorOrange70,
      sisEunTokens.siseunColorOrange80,
      sisEunTokens.siseunColorOrange90,
    ],
    "red-cool-vivid": [
      sisEunTokens.siseunColorRedCoolVivid5,
      sisEunTokens.siseunColorRedCoolVivid10,
      sisEunTokens.siseunColorRedCoolVivid20,
      sisEunTokens.siseunColorRedCoolVivid30,
      sisEunTokens.siseunColorRedCoolVivid40,
      sisEunTokens.siseunColorRedCoolVivid50,
      sisEunTokens.siseunColorRedCoolVivid60,
      sisEunTokens.siseunColorRedCoolVivid70,
      sisEunTokens.siseunColorRedCoolVivid80,
      sisEunTokens.siseunColorRedCoolVivid80,
    ],
    "red-cool": [
      sisEunTokens.siseunColorRedCool5,
      sisEunTokens.siseunColorRedCool10,
      sisEunTokens.siseunColorRedCool20,
      sisEunTokens.siseunColorRedCool30,
      sisEunTokens.siseunColorRedCool40,
      sisEunTokens.siseunColorRedCool50,
      sisEunTokens.siseunColorRedCool60,
      sisEunTokens.siseunColorRedCool70,
      sisEunTokens.siseunColorRedCool80,
      sisEunTokens.siseunColorRedCool90,
    ],
    "red-vivid": [
      sisEunTokens.siseunColorRedVivid5,
      sisEunTokens.siseunColorRedVivid10,
      sisEunTokens.siseunColorRedVivid20,
      sisEunTokens.siseunColorRedVivid30,
      sisEunTokens.siseunColorRedVivid40,
      sisEunTokens.siseunColorRedVivid50,
      sisEunTokens.siseunColorRedVivid60,
      sisEunTokens.siseunColorRedVivid70,
      sisEunTokens.siseunColorRedVivid80,
      sisEunTokens.siseunColorRedVivid80,
    ],
    "red-warm-vivid": [
      sisEunTokens.siseunColorRedWarmVivid5,
      sisEunTokens.siseunColorRedWarmVivid10,
      sisEunTokens.siseunColorRedWarmVivid20,
      sisEunTokens.siseunColorRedWarmVivid30,
      sisEunTokens.siseunColorRedWarmVivid40,
      sisEunTokens.siseunColorRedWarmVivid50,
      sisEunTokens.siseunColorRedWarmVivid60,
      sisEunTokens.siseunColorRedWarmVivid70,
      sisEunTokens.siseunColorRedWarmVivid80,
      sisEunTokens.siseunColorRedWarmVivid80,
    ],
    "red-warm": [
      sisEunTokens.siseunColorRedWarm5,
      sisEunTokens.siseunColorRedWarm10,
      sisEunTokens.siseunColorRedWarm20,
      sisEunTokens.siseunColorRedWarm30,
      sisEunTokens.siseunColorRedWarm40,
      sisEunTokens.siseunColorRedWarm50,
      sisEunTokens.siseunColorRedWarm60,
      sisEunTokens.siseunColorRedWarm70,
      sisEunTokens.siseunColorRedWarm80,
      sisEunTokens.siseunColorRedWarm90,
    ],
    "red": [
      sisEunTokens.siseunColorRed5,
      sisEunTokens.siseunColorRed10,
      sisEunTokens.siseunColorRed20,
      sisEunTokens.siseunColorRed30,
      sisEunTokens.siseunColorRed40,
      sisEunTokens.siseunColorRed50,
      sisEunTokens.siseunColorRed60,
      sisEunTokens.siseunColorRed70,
      sisEunTokens.siseunColorRed80,
      sisEunTokens.siseunColorRed90,
    ],
    "yellow-vivid": [
      sisEunTokens.siseunColorYellowVivid5,
      sisEunTokens.siseunColorYellowVivid10,
      sisEunTokens.siseunColorYellowVivid20,
      sisEunTokens.siseunColorYellowVivid30,
      sisEunTokens.siseunColorYellowVivid40,
      sisEunTokens.siseunColorYellowVivid50,
      sisEunTokens.siseunColorYellowVivid60,
      sisEunTokens.siseunColorYellowVivid70,
      sisEunTokens.siseunColorYellowVivid80,
      sisEunTokens.siseunColorYellowVivid80,
    ],
    "yellow": [
      sisEunTokens.siseunColorYellow5,
      sisEunTokens.siseunColorYellow10,
      sisEunTokens.siseunColorYellow20,
      sisEunTokens.siseunColorYellow30,
      sisEunTokens.siseunColorYellow40,
      sisEunTokens.siseunColorYellow50,
      sisEunTokens.siseunColorYellow60,
      sisEunTokens.siseunColorYellow70,
      sisEunTokens.siseunColorYellow80,
      sisEunTokens.siseunColorYellow90,
    ],
  }
});

export default theme;
